//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaTest
{
    [Serializable]
    public class GripperMsgMsg : Message
    {
        public const string k_RosMessageName = "kinova_test/gripperMsg";
        public override string RosMessageName => k_RosMessageName;

        public float gripperPos;
        public float gripperVel;

        public GripperMsgMsg()
        {
            this.gripperPos = 0.0f;
            this.gripperVel = 0.0f;
        }

        public GripperMsgMsg(float gripperPos, float gripperVel)
        {
            this.gripperPos = gripperPos;
            this.gripperVel = gripperVel;
        }

        public static GripperMsgMsg Deserialize(MessageDeserializer deserializer) => new GripperMsgMsg(deserializer);

        private GripperMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripperPos);
            deserializer.Read(out this.gripperVel);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gripperPos);
            serializer.Write(this.gripperVel);
        }

        public override string ToString()
        {
            return "GripperMsgMsg: " +
            "\ngripperPos: " + gripperPos.ToString() +
            "\ngripperVel: " + gripperVel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
