//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaTest
{
    [Serializable]
    public class KinovaMsgMsg : Message
    {
        public const string k_RosMessageName = "kinova_test/kinovaMsg";
        public override string RosMessageName => k_RosMessageName;

        public float[] jointPos;

        public KinovaMsgMsg()
        {
            this.jointPos = new float[7];
        }

        public KinovaMsgMsg(float[] jointPos)
        {
            this.jointPos = jointPos;
        }

        public static KinovaMsgMsg Deserialize(MessageDeserializer deserializer) => new KinovaMsgMsg(deserializer);

        private KinovaMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.jointPos, sizeof(float), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.jointPos);
        }

        public override string ToString()
        {
            return "KinovaMsgMsg: " +
            "\njointPos: " + System.String.Join(", ", jointPos.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
